---
title: "ACS Data"
author: "Madeline Chang"
date: "2025-07-01"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

Resources:
https://resources.github.com/github-and-rstudio/

https://api.census.gov/data/key_signup.html



## Calling in libraries

```{r setup, include=FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(janitor)
library(lubridate)
library(googlesheets4)
library(rlang)
library(gridExtra)
library(corrplot)
library(forcats)
library(stats)


library(tidycensus)
```

## Finding available measures centered around disability status

```{r}
var<- load_variables(2023, "acs5", cache = TRUE)
var<- var %>%
  mutate(dis = str_detect(concept, 'Disability'),
         dis2 = str_detect(label, 'disability'),
         edu = str_detect(concept, 'Education'),
         edu2 = str_detect(label, 'education'))

var %>%
  filter(edu2 == TRUE | edu == TRUE) %>%  
  group_by(concept) %>%
  summarise(count = n()) %>%
  print(n = 45)
```

----------------------

```{r}
variables<- var %>%
  filter(substr(name, 1, 6) == 'B17003' | substr(name, 1, 6) == 'B23006' | substr(name, 1, 6) == 'B23024' | substr(name, 1, 6) == 'C18120') %>%
  mutate(label = str_remove(label, 'Estimate!!Total:!!')) %>%
  separate_wider_delim(label, delim = "!!", too_few = "align_start", names_sep = "")


# smallest we can do is tract

educ_pov<- variables %>%
  filter(!label2 == 'Total:') %>%
  filter(substr(name, 1, 6) == 'B17003') %>%
  mutate(label1 = case_when(str_detect(label1, "above") ~ "above_pov",
                           str_detect(label1, "below") ~ "below_pov"),
         label2 = case_when(str_detect(label2, "Male")~ "M",
                            str_detect(label2, "Female") ~ "F"),
         label3 = case_when(str_detect(label3, "Less than")~ "less_hs",
                            str_detect(label3, "High school grad")~ "hs",
                            str_detect(label3, "Some college")~ "some_tert",
                            str_detect(label3, "or higher")~ "tert_plus")) %>%
  select(name, label1, label2, label3) %>%
  drop_na()


educ_emp<- variables %>%
  filter(!label2 == 'Total:') %>%
  filter(substr(name, 1, 6) == "B23006") %>%
  mutate(label1 = case_when(str_detect(label1, "Less than")~ "less_hs",
                            str_detect(label1, "High school grad")~ "hs",
                            str_detect(label1, "Some college")~ "some_tert",
                            str_detect(label1, "or higher")~ "tert_plus"),
         label2 = case_when(str_detect(label2, 'In labor')~ "in_labor",
                            str_detect(label2, "Not in")~ "not_labor"),
         label3 = case_when(str_detect(label3, "Armed")~ "arm_force",
                            str_detect(label3, "Civil") & str_detect(label4, "Employed")~ "civil_emp",
                            str_detect(label3, "Civil") & str_detect(label4, "Unemployed")~ "civil_un")) %>%
  select(name, label1, label2, label3) %>% 
  filter(!is.na(label3) | label2 == "not_labor")

pov_dis_emp<- variables %>%
  filter(!label2 == 'Total:') %>%
  filter(substr(name, 1, 6) == "B23024") %>%
  mutate(label1 = case_when(str_detect(label1, "above") ~ "above_pov",
                           str_detect(label1, "below") ~ "below_pov"),
         label2 = case_when(str_detect(label2, "With a dis")~ "dis",
                            str_detect(label2, "No dis")~ "no_dis"),
         label3 = case_when(str_detect(label3, 'In labor')~ "in_labor",
                            str_detect(label3, "Not in")~ "not_labor"),
         label4 = case_when(str_detect(label4, "Armed")~ "arm_force",
                            str_detect(label4, "Civil") & str_detect(label5, "Employed")~ "civil_emp",
                            str_detect(label4, "Civil") & str_detect(label5, "Unemployed")~ "civil_un")) %>%
  select(name, label1, label2, label3, label4) %>%
  filter(!is.na(label4) | label2 == "no_dis" & !is.na(label3))


emp_dis<- variables %>%
  filter(!label2 == 'Total:') %>%
  filter(substr(name, 1, 6) == "C18120") %>%
  mutate(label1 = case_when(str_detect(label1, 'In the labor')~ "in_labor",
                            str_detect(label1, "Not in")~ "not_labor"),
         label3 = case_when(str_detect(label3, "With a dis") | str_detect(label2, "With a dis")~ "dis",
                            str_detect(label3, "No dis") | str_detect(label2, "No dis")~ "no_dis"),
         label2 = case_when(str_detect(label2, "Employed")~ "emp",
                            str_detect(label2, "Unemp")~ "unemp")) %>%
  select(name, label1, label2, label3)
```

```{r}
educ_emp_data <- get_acs(geography='tract', state = "IL", variables = c(educ_emp$name), survey = "acs5", year = 2023, cache = TRUE)

educ_pov_data<- get_acs(geography='tract', state = "IL", variables = c(educ_pov$name), survey = "acs5", year = 2023, cache = TRUE)

emp_dis_data <- get_acs(geography='tract', state = "IL", variables = c(emp_dis$name), survey = "acs5", year = 2023, cache = TRUE)

pov_dis_emp_data<- get_acs(geography='tract', state = "IL", variables = c(pov_dis_emp$name), survey = "acs5", year = 2023, cache = TRUE)
```

```{r}
a<- educ_emp_data %>%
  pivot_wider(names_from = variable, values_from = c(estimate, moe)) %>%
  select(!NAME)

b<- educ_pov_data %>%
  pivot_wider(names_from = variable, values_from = c(estimate, moe))%>%
  select(!NAME)

c<- emp_dis_data %>%
  pivot_wider(names_from = variable, values_from = c(estimate, moe))%>%
  select(!NAME)

d<- pov_dis_emp_data %>%
  pivot_wider(names_from = variable, values_from = c(estimate, moe))%>%
  select(!NAME)
```

```{r}
e<- a %>%
  inner_join(b, by = join_by(GEOID)) %>%
  inner_join(c, by = join_by(GEOID)) %>%
  inner_join(d, by = join_by(GEOID))

```


```{r}
# PUMS data example (takes a while to run, and we would pull in smaller batches of columns)

pums_var<- pums_variables %>% 
  filter(year == 2023, survey == "acs5") %>%
  distinct(var_code, var_label, data_type, level) %>% 
  filter(level == "person")

pums<- get_pums(variables = c(pums_var$var_code[1:4]), year = 2023, state = "IL", survey = "acs5", recode = TRUE)

```

